config/routes.rb
Rails.application.routes.draw do
  root "homes#index"

  resources :all_notices
  
  #알림 : 전체 삭제
  get '/new_notifications/read_all' => 'new_notifications#read_all'
  #알림
  resources :new_notifications
  
  resources :qnas do
    post "/report_qna", to: "report_qnas#report_qna_toggle"
    put "/like", to:    "qnas#upvote"
    put "/dislike", to: "qnas#downvote"
  end
  
  resources :searches
  resources :search_all_notices
  resources :search_qnas
  
  resources :bulletins do
    resources :posts do
      put "/like", to:    "posts#upvote"
      put "/dislike", to: "posts#downvote"
      collection do
        get :search
      end
    end
  end
  
  resources :comments do
    put "/like", to:    "comments#upvote"
    put "/dislike", to: "comments#downvote"
    post "/report_comment", to: "report_comments#report_comment_toggle"
    post "/comment_destroys", to: "comment_destroys#comment_destroy_toggle"
  end
  
  resources :bulletins do
    resources :posts
    post "/posts/:post_id/report", to: "reports#report_toggle"
    post "/posts/:post_id/alarm_qna", to: "alarm_qnas#alarm_qna_toggle"
    post "/posts/:post_id/restore", to: "posts#restore"
  end
  
  resources :posts do
    resources :comment_qnas do
        put "/like", to:    "comment_qnas#upvote"
        put "/dislike", to: "comment_qnas#downvote"
      end
  end
  
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  get '/users/message'
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
  #mount ActionCable.server => '/cable'
  
  get '/users/user_list'
  
  #devise_for :users로 인해 별도의 라우터 설정 필요 171012 상열
  resources :users, :only => [:show]
  
  #이미지 업로드 (AWS S3 연동)
  post '/tinymce_assets' => 'tinymce_assets#create'
  
  devise_for :admins
  # 어드민 페이지 및 rails_db
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/views/meta/_meta_all_notice_index.html.erb
<%# 메타태그 속성(검색엔진 반영 전용) %>
<!-- 일반 웹브라우저 -->
<meta name="copyright" content=".:: 강원대학교 커뮤니티 ::."/>
<meta property="title" content="공지사항"/>
<meta name="classification" content="공지사항">
<meta name="description" content="커뮤니티 소식을 알려드립니다!"/>
<meta name="keywords" content="우리대학교는세계제이이이이일,멋쟁이 사자처럼,강원대,강원대학교,강원대학교커뮤니티,강원대커뮤니티,강원대대나무숲,강원대춘천,강원대춘천캠,강원대춘천캠퍼스,춘천대학교,강대,강대라이크,Kangwon National University Community,Kangwon University Community,Kangwon Community,Kangwon University,Kangwon Univ.,Kangwon Nati. Univ.,Kangwon,강원도,춘천,국립대,국립대 커뮤니티,지거국,지거국 커뮤니티"/>

<!-- 페이스북 / 카카오톡 등 -->
<meta property="og:site_name" content=".:: 강원대학교 커뮤니티 ::."/>
<meta property="og:title" content="공지사항"/>
<meta property="og:description" content="커뮤니티 소식을 알려드립니다!"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="<%= request.protocol %><%= request.host %><%= all_notices_path %>"/>

app/views/meta/_meta_all_notice_show.html.erb
<%# 메타태그 속성(검색엔진 반영 전용) %>
<!-- 일반 웹브라우저 -->
<meta name="copyright" content=".:: 강원대학교 커뮤니티 ::.">
<meta name="classification" content="공지사항">
<meta property="title" content="<%= truncate( raw( sanitize(post.title, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 50, :omission => "...") %>">
<meta name="description" content="<%= truncate( raw( sanitize(post.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 90, :omission => "...") %>">
<meta name="keywords" content="우리대학교는세계제이이이이일,멋쟁이 사자처럼,강원대,강원대학교,강원대학교커뮤니티,강원대커뮤니티,강원대대나무숲,강원대춘천,강원대춘천캠,강원대춘천캠퍼스,춘천대학교,강대,강대라이크,Kangwon National University Community,Kangwon University Community,Kangwon Community,Kangwon University,Kangwon Univ.,Kangwon Nati. Univ.,Kangwon,강원도,춘천,국립대,국립대 커뮤니티,지거국,지거국 커뮤니티">

<!-- 페이스북 / 카카오톡 등 -->
<meta property="og:site_name" content=".:: 강원대학교 커뮤니티 ::."/>
<meta property="og:title" content="<%= truncate( raw( sanitize(post.title, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 50, :omission => "...") %>">
<meta property="og:description" content="<%= truncate( raw( sanitize(post.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 90, :omission => "...") %>">
<meta property="og:type" content="website">
<meta property="og:url" content="<%= request.protocol %><%= request.host %><%= all_notice_path %>">

app/views/meta/_meta_post_index.html.erb
<%# 메타태그 속성(검색엔진 반영 전용) %>
<!-- 일반 웹브라우저 -->
<meta name="copyright" content=".:: 강원대학교 커뮤니티 ::."/>
<meta name="classification" content="<%= bulletin.title %>">
<meta property="title" content="<%= bulletin.title %>"/>
<meta name="description" content="<%= bulletin.content %>"/>
<meta name="keywords" content="우리대학교는세계제이이이이일,멋쟁이 사자처럼,강원대,강원대학교,강원대학교커뮤니티,강원대커뮤니티,강원대대나무숲,강원대춘천,강원대춘천캠,강원대춘천캠퍼스,춘천대학교,강대,강대라이크,Kangwon National University Community,Kangwon University Community,Kangwon Community,Kangwon University,Kangwon Univ.,Kangwon Nati. Univ.,Kangwon,강원도,춘천,국립대,국립대 커뮤니티,지거국,지거국 커뮤니티"/>

<!-- 페이스북 / 카카오톡 등 -->
<meta property="og:site_name" content=".:: 강원대학교 커뮤니티 ::."/>
<meta property="og:title" content="<%= bulletin.title %>"/>
<meta property="og:description" content="<%= bulletin.content %>"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="<%= request.protocol %><%= request.host %><%= bulletin_posts_path %>"/>

app/views/meta/_meta_post_show.html.erb
<%# 메타태그 속성(검색엔진 반영 전용) %>
<!-- 일반 웹브라우저 -->
<meta name="copyright" content=".:: 강원대학교 커뮤니티 ::.">
<meta name="classification" content="<%= post.bulletin.title %>">
<meta property="title" content="<%= truncate( raw( sanitize(post.title, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 50, :omission => "...") %>">
<meta name="description" content="<%= truncate( raw( sanitize(post.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 90, :omission => "...") %>">
<meta name="keywords" content="우리대학교는세계제이이이이일,멋쟁이 사자처럼,강원대,강원대학교,강원대학교커뮤니티,강원대커뮤니티,강원대대나무숲,강원대춘천,강원대춘천캠,강원대춘천캠퍼스,춘천대학교,강대,강대라이크,Kangwon National University Community,Kangwon University Community,Kangwon Community,Kangwon University,Kangwon Univ.,Kangwon Nati. Univ.,Kangwon,강원도,춘천,국립대,국립대 커뮤니티,지거국,지거국 커뮤니티">

<!-- 페이스북 / 카카오톡 등 -->
<meta property="og:site_name" content=".:: 강원대학교 커뮤니티 ::.">
<meta property="og:title" content="<%= truncate( raw( sanitize(post.title, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 50, :omission => "...") %>">
<meta property="og:description" content="<%= truncate( raw( sanitize(post.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 90, :omission => "...") %>">
<meta property="og:type" content="website">
<meta property="og:url" content="<%= request.protocol %><%= request.host %><%= bulletin_post_path %>">

app/views/meta/_meta_show.html.erb
<%# 메타태그 속성(검색엔진 반영 전용) %>
<!-- 일반 웹브라우저 -->
<meta name="copyright" content=".:: 강원대학교 커뮤니티 ::."/>
<meta property="title" content="<%= post.title.truncate(50, omission: '...') %>"/>
<meta name="description" content="<%= post.content.html_safe.truncate(90, omission: '...') %>"/>
<meta name="keywords" content="우리대학교는세계제이이이이일,멋쟁이 사자처럼,강원대,강원대학교,강원대학교커뮤니티,강원대커뮤니티,강원대대나무숲,강원대춘천,강원대춘천캠,강원대춘천캠퍼스,춘천대학교,강대,강대라이크,Kangwon National University Community,Kangwon University Community,Kangwon Community,Kangwon University,Kangwon Univ.,Kangwon Nati. Univ.,Kangwon,강원도,춘천,국립대,국립대 커뮤니티,지거국,지거국 커뮤니티"/>

<!-- 페이스북 / 카카오톡 등 -->
<meta property="og:site_name" content=".:: 강원대학교 커뮤니티 ::."/>
<meta property="og:title" content="<%= post.title.truncate(50, omission: '...') %>"/>
<meta property="og:description" content="<%= post.content.html_safe.truncate(90, omission: '...') %>"/>
<meta property="og:type" content="website"/>