config/routes.rb
Rails.application.routes.draw do
  root "homes#index"

  resources :all_notices
  
  #알림 : 전체 삭제
  get '/new_notifications/read_all' => 'new_notifications#read_all'
  #알림
  resources :new_notifications
  
  resources :qnas do
    post "/report_qna", to: "report_qnas#report_qna_toggle"
    put "/like", to:    "qnas#upvote"
    put "/dislike", to: "qnas#downvote"
  end
  
  resources :searches
  resources :search_all_notices
  resources :search_qnas
  
  resources :bulletins do
    resources :posts do
      put "/like", to:    "posts#upvote"
      put "/dislike", to: "posts#downvote"
      collection do
        get :search
      end
    end
  end
  
  resources :comments do
    put "/like", to:    "comments#upvote"
    put "/dislike", to: "comments#downvote"
    post "/report_comment", to: "report_comments#report_comment_toggle"
    post "/comment_destroys", to: "comment_destroys#comment_destroy_toggle"
  end
  
  resources :bulletins do
    resources :posts
    post "/posts/:post_id/report", to: "reports#report_toggle"
    post "/posts/:post_id/alarm_qna", to: "alarm_qnas#alarm_qna_toggle"
    post "/posts/:post_id/restore", to: "posts#restore"
  end
  
  resources :posts do
    resources :comment_qnas do
        put "/like", to:    "comment_qnas#upvote"
        put "/dislike", to: "comment_qnas#downvote"
      end
  end
  
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  get '/users/message'
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
  #mount ActionCable.server => '/cable'
  
  get '/users/user_list'
  
  #devise_for :users로 인해 별도의 라우터 설정 필요 171012 상열
  resources :users, :only => [:show]
  
  #이미지 업로드 (AWS S3 연동)
  post '/tinymce_assets' => 'tinymce_assets#create'
  
  devise_for :admins
  # 어드민 페이지 및 rails_db
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/all_notice.rb
class AllNotice < ApplicationRecord
    # 삭제되는 내용 기록
    acts_as_paranoid
    # 검색엔진 (Sunspot)
    searchable do
        text :title, :default_boost => 2 #제목
        text :content # 내용
        time :created_at
        text :user_name # 유저 닉네임
    end
    # 게시글 목록
    paginates_per 10
    # 조회수
    is_impressionable
    # 대댓글이 지원되는 댓글 Gem
    acts_as_commentable
    
    #has_many :impressions, :as=>:impressionable
    belongs_to :user
    
    #def impression_count
    #    impressions.size
    #end
 
   #def unique_impression_count
       # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
       # so getting keys from the hash and calculating the number of keys
   #    impressions.group(:ip_address).size.keys.length #TESTED
   #end
end

app/controllers/all_notices_controller.rb
class AllNoticesController < ApplicationController
  #before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_all_notice, only: [:show, :edit, :update, :destroy]
  impressionist actions: [:show], unique: [:session_hash]
  #before_action :log_impression, :only=> [:show]
 
  #def log_impression
  #  @hit_post = AllNotice.find(params[:id])
    # this assumes you have a current_user method in your authentication system
  #  @hit_post.impressions.create(ip_address: request.remote_ip,user_id:current_user.id)
  #end

  # GET /all_notices
  # GET /all_notices.json
  def index
    @all_notices = AllNotice.order("created_at DESC").page(params[:page]).per(10)
  end

  # GET /all_notices/1
  # GET /all_notices/1.json
  def show
    @all_notices = AllNotice.order("created_at DESC").page(params[:page]).per(5)
    
    # 댓글
    @all_notice = AllNotice.find(params[:id])
    if user_signed_in?
      @new_comment  = Comment.build_from(@all_notice, current_user.id, "")
    end
  end

  # GET /all_notices/new
  def new
    @all_notice = AllNotice.new
  end

  # GET /all_notices/1/edit
  def edit
  end

  # POST /all_notices
  # POST /all_notices.json
  def create
    @all_notice = AllNotice.new(all_notice_params)
    @all_notice.user_name = current_user.nickname

    respond_to do |format|
      if @all_notice.save
        format.html { redirect_to @all_notice, notice: '게시글이 성공적으로 작성되었습니다.' }
        format.json { render :show, status: :created, location: @all_notice }
      else
        format.html { render :new }
        format.json { render json: @all_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /all_notices/1
  # PATCH/PUT /all_notices/1.json
  def update
    respond_to do |format|
      if @all_notice.update(all_notice_params)
        format.html { redirect_to @all_notice, notice: '게시글이 성공적으로 수정되었습니다.' }
        format.json { render :show, status: :ok, location: @all_notice }
      else
        format.html { render :edit }
        format.json { render json: @all_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /all_notices/1
  # DELETE /all_notices/1.json
  def destroy
    if current_user.has_role? :admin
      @all_notice.really_destroy!
    end
    
    respond_to do |format|
      format.html { redirect_to all_notices_url, notice: '게시글이 성공적으로 삭제되었습니다.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_all_notice
      @all_notice = AllNotice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def all_notice_params
      params[:all_notice][:user_id] = current_user.id
      params.require(:all_notice).permit(:title, :content, :user_id, :notice, :all_notice, :comment_permission, :title_tag_permission, :user_name)
    end
end

app/helpers/all_notices_helper.rb
module AllNoticesHelper
end

app/views/all_notices/_form.html.erb
<%= form_with(model: all_notice, local: true) do |form| %>
  <div class="field">
    <%= form.label :제목 %>
    <%= form.text_field :title, id: :all_notice_title, class: "form-control no-border" %><br/>
  </div>

  <div class="field">
    <%= form.label :내용 %>
    <%= tinymce :language => "en" %>
    <%= form.text_area :content, id: :all_notice_content, class: "form-control tinymce", rows: "10" %>
  </div>
  
  <% if can? :for_admin, @all_notice %>
    <div class="col-12 col-sm-8 col-md-5" style="background-color: #ffd4d4; margin-top: 30px; padding: 10px;"><font color="red"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 어드민 전용 : 해당 게시글 설정</font></div>
    <div align="left" style="margin-top: 10px;">
      <%= form.label :notice, "1) 공지사항 설정" %> <%= form.check_box :notice, id: :all_notice_notice %><br/>
      <%= form.label :all_notice, "2) 전체 게시물 공지사항 설정" %> <%= form.check_box :all_notice, id: :all_notice_all_notice %><br/>
      <%= form.label :comment_permission, "3) 댓글 활성 여부" %> <%= form.check_box :comment_permission, id: :all_notice_comment_permission %><br/>
      <%= form.label :title_tag_permission, "4) 제목 태그 허용 여부" %> <%= form.check_box :title_tag_permission, id: :all_notice_title_tag_permission %>
    </div>
  <% end %>
  
  <center>
  <div class="form-actions" style="margin-top: 20px;">
    <%= form.button :글쓰기, class: "btn btn-primary" %>
  <% end %>
    <%= link_to '목록', @all_notice, class: "btn btn-secondary" %>
  </div>
</center>

app/views/all_notices/edit.html.erb
<div class="board hidden-sm-down" style="background: url('/img/title_img9.jpg') no-repeat fixed; background-size: 100% 70%; background-position:0px -180px;">
  <div class="container" align="left">
    <span  class="post_title"><%= link_to "공지사항", all_notices_path, class: "board_title" %></span>
  </div>
</div>
<div class="board_mobile hidden-md-up" style="background: url('/img/title_img9.jpg') no-repeat center center/cover scroll;">
  <span class="post_title"><%= link_to "공지사항", all_notices_path, class: "board_title" %></span>
</div>

<% #경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<% if alert %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    <% elsif notice %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #43AC6A; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
<% end %>

<div class="container" style="margin-top:30px; margin-bottom: 100px;">
  <div class="alert alert-info" role="alert">
    <strong><i class="far fa-edit" aria-hidden="true"></i> 게시글 수정</strong>
  </div>
      <%= render 'form', all_notice: @all_notice %>
</div>

app/views/all_notices/index.html.erb
<div class="board hidden-sm-down" style="background: url('/img/title_img9.jpg') no-repeat fixed; background-size: 100% 70%; background-position:0px -180px;">
  <div class="container" align="left">
    <span  class="post_title"><%= link_to "공지사항", all_notices_path, class: "board_title" %></span>
  </div>
</div>
<div class="board_mobile hidden-md-up" style="background: url('/img/title_img9.jpg') no-repeat center center/cover scroll;">
  <span class="post_title"><%= link_to "공지사항", all_notices_path, class: "board_title" %></span>
</div>

<% #경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<% if alert %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    <% elsif notice %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #43AC6A; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
<% end %>

<%# 메타태그 속성(검색엔진 반영 전용) %>
<%= render 'meta/meta_all_notice_index' %>

<div class="container" style="margin-bottom: 100px;">
  <div align="right">
    <p class="badge badge-pill badge-success hidden-xs-down" style="margin-top:20px; margin-bottom: 20px;"><i class="fa fa-clock-o" aria-hidden="true"></i> 현재 시간 </span> <span><%= Time.zone.now.strftime('%Y-%m-%d %H:%M:%S') %></p>
  </div>
  
  <%# 전체 공지사항 %>
  <% @all_notices.each do |post| %>
    <% if post.all_notice == true %>
      <div class="row table_notice separate_board">
        <% # 공지 Badge %>
        <div align="center" class="col-0 col-sm-0 col-md-1 hidden-sm-down" style="padding: 10px;">
          <%= content_tag(:span, '<span class="badge badge-success">전체공지</span>'.html_safe, class: "etc", align: "center", style: "margin-top: 5px;") %>
        </div>
        <%= render "all_notices/list/board_all_notice_index", post: post %>
      </div>
    <% end %>
  <% end %>
  <% if @all_notices.empty? %>
    <h2 class="text-center" style="margin-top: 30px;">게시글이 없습니다.</h2>
  <% else %>
    <%# 공지 게시글 %>
    <% @all_notices.each do |post| %>
      <% if post.notice == true %>
        <div class="row table_sub_notice separate_board" onMouseOver="this.style.backgroundColor='#ECECEC'" onMouseOut="this.style.backgroundColor='#FFFFFF'">
          <% # 공지 Badge %>
          <div align="center" class="col-0 col-sm-0 col-md-1 hidden-sm-down" style="padding: 10px;">
            <%= content_tag(:span, "공지사항", class: "badge badge-primary etc", align: "center", style: "margin-top: 5px;") %>
            <!-- <span style="margin-top: 5px;" align="center" class="badge badge-primary etc">공지사항</span> -->
          </div>
          <div align="center" class="col-0 col-sm-0 col-md-2 etc hidden-sm-down" style="padding: 10px;">
            <%= render 'posts/special/nickname_post_index', post: post %>
          </div>
          <%= render "all_notices/list/board_notice_normal_index", post: post %>
        </div>
      <% end %>
    <% end %>

    <%# 일반 게시글 %>
    <% if user_signed_in? %>
      <% if current_user.has_role? :admin %>
        <% @all_notices.with_deleted.each do |post| %>
          <%= render 'all_notices/list/notice_index', post: post %>
        <% end %>
      <% else %>
        <% @all_notices.each do |post| %>
          <%= render 'all_notices/list/notice_index', post: post %>
        <% end %>
      <% end %>
    <% else %>
      <% @all_notices.each do |post| %>
        <%= render 'all_notices/list/notice_index', post: post %>
      <% end %>
    <% end %>
  <% end %>

  <% if can? :new, @all_notices %>
    <div align="right" style="margin-top: 10px;">
      <%= link_to "글 쓰기", new_all_notice_path, class: "btn btn-primary" %>
    </div>
  <% end %>
  
  <div class="d-flex flex-column", style="margin-bottom: 10px; margin-top: 30px">
    <%= paginate @all_notices %>
  </div>
  
  <div style="margin-top: 20px; margin-bottom: 100px;">
    <%= render 'search-form/all_notice_search' %>
  </div>
</div>

app/views/all_notices/new.html.erb
<div class="board hidden-sm-down" style="background: url('/img/title_img9.jpg') no-repeat fixed; background-size: 100% 70%; background-position:0px -180px;">
  <div class="container" align="left">
    <span  class="post_title"><%= link_to "공지사항", all_notices_path, class: "board_title" %></span>
  </div>
</div>
<div class="board_mobile hidden-md-up" style="background: url('/img/title_img9.jpg') no-repeat center center/cover scroll;">
  <span class="post_title"><%= link_to "공지사항", all_notices_path, class: "board_title" %></span>
</div>

<% #경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
    <% if alert %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    
    <% elsif notice %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #43AC6A; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    
    <% elsif @all_notice.errors.any? %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    제목 혹은 내용을 입력해주세요.
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
  <% end %>
  
<div class="container" style="margin-top:30px; margin-bottom: 100px;">
    <%= render 'form', all_notice: @all_notice %>
</div>

app/views/all_notices/show.html.erb
<div class="board hidden-sm-down" style="background: url('/img/title_img9.jpg') no-repeat fixed; background-size: 100% 70%; background-position:0px -180px;">
  <div class="container" align="left">
    <span  class="post_title"><%= link_to "공지사항", all_notices_path, class: "board_title" %></span>
  </div>
</div>
<div class="board_mobile hidden-md-up" style="background: url('/img/title_img9.jpg') no-repeat center center/cover scroll;">
  <span class="post_title"><%= link_to "공지사항", all_notices_path, class: "board_title" %></span>
</div>

<% #경고메세지 출력 (아이디, 비밀번호 잘못 칠 시 등등...) %>
<% if alert %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #FF4B5C; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
    <% elsif notice %>
    <div class="alert alert-danger tlert-dismissible fade show text-center" style="padding: 10px; background-color: #43AC6A; color: white; border-radius: 0; margin-bottom: 0; border: 0">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    </div>
<% end %>

<%# 메타태그 속성(검색엔진 반영 전용) %>
<%= render 'meta/meta_all_notice_show', post: @all_notice %>

<div class="container" style="margin-top:30px; margin-bottom: 100px;">
    <% if @all_notice.title_tag_permission == true %>
        <h4><%= content_tag(:div, @all_notice.title.html_safe ) %></h4>
    <% else %>
        <h4><%= content_tag(:div, truncate( raw( sanitize(@all_notice.title, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 100, :omission => "..."), class: "etc" ) %></h4><br/>
    <% end %>
    <div class="row">
        <% # [그리드] PC, 모바일 공통에서 볼 경우 : 닉네임 %>
        <div class="col-4 etc">
            <%= render 'posts/special/nickname_all_notice_show' %>
        </div>
        <% # [그리드] Only 모바일 에서 볼 경우 : 글 작성시간 %>
        <div class="col-8" align="right"><span style="margin-right: 10px;"><%= @all_notice.created_at.in_time_zone("Asia/Seoul").strftime('%Y-%m-%d %H:%M') %></span>
        |<i class="fas fa-eye" aria-hidden="true" style="margin-left: 15px;"></i> <%= "#{@all_notice.impressionist_count}" %></div>
    </div>
    <hr/>
      
    <%= content_tag(:div, @all_notice.content.html_safe, :class => "panel-body", :style => "margin-top: 30px; margin-bottom: 70px;") %>
    
    <%# 광고 %>
    <%#= render 'posts/special/ad_show' %>
    
    <div class= "row">
        <div class="col-7 col-md-6" align="left">
            <%= link_to '목록', all_notices_path, class: "btn btn-secondary btn-sm" %>
            <% if can? :update, @all_notice %>
                <%= link_to '수정', edit_all_notice_path(@all_notice), class: "btn btn-secondary btn-sm" %>
            <% end %>
            <% if can? :destroy, @all_notice %>
                <%= link_to "삭제", @all_notice, method: :delete, data: { confirm: '삭제 시 로그에 안남는 채로 삭제됩니다. 정말로 영원히 삭제하시겠습니까?' }, class: "btn btn-secondary btn-sm" %>
            <% end %>
        </div>
        <div class="col-5 col-md-6" align="right">
            <% if can? :new, @all_notice %>
                <%= link_to '글 쓰기', new_all_notice_path, class: "btn btn-primary btn-sm", align: "right" %>
            <% end %>
        </div>
    </div>
    
    <% if @all_notice.comment_permission == true %>
        <% if user_signed_in? %>
            <%= render partial: "all_notices/list/comment_vote_list" %>
        <% else %>
            <div align="center" style="margin-top: 30px;">
        <hr/>
            <i class="fas fa-lock"></i> 댓글을 보시려면 로그인 하셔야 합니다.
        </div>
        <% end %>
    <% else %>
        <div align="center" style="margin-top: 30px;">
        <hr/>
            <i class="fas fa-lock"></i> 댓글이 허용되지 않은 공지사항 입니다.
        </div>
    <% end %>
    
    <div style="margin-top: 60px;"></div>
    
    <%# 다른 게시물들 %>
    <% if @all_notices.empty? %>
        <h2 class="text-center" style="margin-top: 30px;">게시글이 없습니다.</h2>
    <% else %>
        <div style="margin-top: 5px;"></div>
        <%# 전체 공지사항 %>
        <% @all_notices.each do |post| %>
          <% if post.all_notice == true %>
            <div class="row table_notice separate_board">
              <% # 공지 Badge %>
              <div align="center" class="col-0 col-sm-0 col-md-1 hidden-sm-down" style="padding: 10px;">
                <%= content_tag(:span, '<span class="badge badge-success">전체공지</span>'.html_safe, class: "etc", align: "center", style: "margin-top: 5px;") %>
              </div>
              <%= render "all_notices/list/board_all_notice_index", post: post %>
            </div>
          <% end %>
        <% end %>
        
        <%# 일반 게시글 %>
        <% @all_notices.each do |post| %>
            <div class="row separate_board" bgcolor="white" onMouseOver="this.style.backgroundColor='#ECECEC'" onMouseOut="this.style.backgroundColor='#FFFFFF'">
                <% # 글 번호 %>
                <div align="center" class="col-0 col-sm-0 col-md-1 hidden-sm-down" style="padding: 10px;">
                    <%= post.id %>
                </div>
                
                <% # 게시글 제목 %>
                <div align="left" class="col-6 col-sm-5 col-md-7 etc" style="padding: 10px;">
                    <%= link_to post do %>
                        <% if post.title_tag_permission == true %>
                            <%= content_tag(:div, post.title.html_safe, class: "etc") %>
                        <% else %>
                            <%= content_tag(:div, truncate( raw( sanitize(post.title, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 100, :omission => "..."), class: "etc" ) %>
                        <% end %>
                    <% end %>
                </div>
                
                <div class="row col-6 col-sm-7 col-md-4" style="margin-left: 15px;">
                    <% # 댓글 %>
                    <div align="left" class="col-6 col-sm-3 col-md-4 arrow_left separate_board_inside">
                        <i class="far fa-comments"></i>
                        <% if post.comment_permission == true %>
                            <% if post.comment_threads.count < 1000 %>
                                <%= post.comment_threads.count %>
                            <% else %>
                                <small><b><%= post.comment_threads.count/1000 %> K</b></small>
                            <% end %>
                        <% else %>
                            ×
                        <% end %>
                    </div>
                    
                    <% # 조회수 %>
                    <div align="left" class="col-6 col-sm-3 col-md-4 separate_board_inside">
                        <i class="fas fa-eye"></i>
                        <% if post.impressionist_count < 1000 %>
                            <%= "#{post.impressionist_count}" %>
                        <% else %>
                            <b><%= "#{post.impressionist_count/1000} K" %></b>
                        <% end %>
                    </div>
                    
                    <% # 시간 %>
                    <div align="left" class="col-0 col-sm-6 col-md-4 separate_board_inside hidden-xs-down">
                        <small><%= "#{time_ago_in_words(post.created_at)} 전" %></small>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
    
    <div class="d-flex flex-column", style="margin-bottom: 10px; margin-top: 30px;">
        <%= paginate @all_notices %>
    </div>
    
    <%= render 'search-form/all_notice_search' %>
</div>