config/routes.rb
Rails.application.routes.draw do
  root "homes#index"

  resources :all_notices
  
  #알림 : 전체 삭제
  get '/new_notifications/read_all' => 'new_notifications#read_all'
  #알림
  resources :new_notifications
  
  resources :qnas do
    post "/report_qna", to: "report_qnas#report_qna_toggle"
    put "/like", to:    "qnas#upvote"
    put "/dislike", to: "qnas#downvote"
  end
  
  resources :searches
  resources :search_all_notices
  resources :search_qnas
  
  resources :bulletins do
    resources :posts do
      put "/like", to:    "posts#upvote"
      put "/dislike", to: "posts#downvote"
      collection do
        get :search
      end
    end
  end
  
  resources :comments do
    put "/like", to:    "comments#upvote"
    put "/dislike", to: "comments#downvote"
    post "/report_comment", to: "report_comments#report_comment_toggle"
    post "/comment_destroys", to: "comment_destroys#comment_destroy_toggle"
  end
  
  resources :bulletins do
    resources :posts
    post "/posts/:post_id/report", to: "reports#report_toggle"
    post "/posts/:post_id/alarm_qna", to: "alarm_qnas#alarm_qna_toggle"
    post "/posts/:post_id/restore", to: "posts#restore"
  end
  
  resources :posts do
    resources :comment_qnas do
        put "/like", to:    "comment_qnas#upvote"
        put "/dislike", to: "comment_qnas#downvote"
      end
  end
  
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  get '/users/message'
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
  #mount ActionCable.server => '/cable'
  
  get '/users/user_list'
  
  #devise_for :users로 인해 별도의 라우터 설정 필요 171012 상열
  resources :users, :only => [:show]
  
  #이미지 업로드 (AWS S3 연동)
  post '/tinymce_assets' => 'tinymce_assets#create'
  
  devise_for :admins
  # 어드민 페이지 및 rails_db
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def index
        @search_post = Post.all.search do
            fulltext params[:search]
            paginate :page => params[:page], :per_page => 10
            without(:bulletin_id, [15, 16])
            order_by :created_at, :desc
        end
        
        @search_post_results = @search_post.results
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/index.html.erb
<div class="board hidden-sm-down" style="background: url('/img/title_img2.jpg') no-repeat fixed; background-size: 100% 70%; background-position:0px -180px;">
  <div class="container" align="left">
    <span class="post_title"><%= link_to "게시글 검색결과", searches_path, class: "board_title" %></span>
  </div>
</div>
<div class="board_mobile hidden-md-up" style="background: url('/img/title_img2.jpg') no-repeat center center/cover scroll;">
  <span class="post_title"><%= link_to "게시글 검색결과", searches_path, class: "board_title" %></span>
</div>

<div class="container">
  <div align="right">
    <p class="badge badge-pill badge-success hidden-xs-down" style="margin-top:20px; margin-bottom: 20px;"><i class="fa fa-clock-o" aria-hidden="true"></i> 현재 시간 </span> <span><%= Time.zone.now.strftime('%Y-%m-%d %H:%M:%S') %></p>
  </div>
  
  <div class="hidden-md-up" style="margin-top: 10px;"></div>
  <%# 검색결과 %>
  <div class="row">
    <div class="col-12 col-sm-12 col-md-12" align="center">검색결과<hr/></div>
  </div>
  
  <% if @search_post_results.empty? %>
    <h2 align="center" style="margin-top: 50px;">검색결과가 없습니다.</h2>
  <% else %>
    <div class="fade-anim">
      <% @search_post_results.each do |post| %>
        <div class="row" onMouseOver="this.style.backgroundColor='#ECECEC'" onMouseOut="this.style.backgroundColor='#FFFFFF'">
          <%# 게시글 제목 %>
          <div align="left" class="col-12 col-sm-12 col-md-12 etc", style="margin-top: 10px;">
          <h5>
          <b>
            <% if post.reports.size >= post.num %>
              <% if can? :for_admin, post %>
                <%= link_to bulletin_post_path(post.bulletin, post) do %>
                  <%= content_tag(:div, post.title, class: "etc", style: "color: red") %>
                <% end %>
              <% else %>
                <font color="#6E6E6E"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 블라인드 처리 된 게시글입니다.</font>
              <% end %>
            <% else %>
              <%= link_to bulletin_post_path(post.bulletin, post) do %>
                <%= content_tag(:div, post.title, class: "etc") %>
              <% end %>
            <% end %>
          </b>
          </h5>
          </div>
          
          <%# 게시글 내용 %>
          <div align="left" class="col-12 col-sm-12 col-md-12 etc", style="margin-top: 10px;">
            <% if post.reports.size >= post.num %>
              <% if current_user.has_role? :admin %>
                <%= content_tag(:div, truncate( raw( sanitize(post.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 70, :omission => "..."), class: "etc", style: "color: red") %>
              <% else %>
                <font color="#6E6E6E"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 블라인드 처리 된 게시글입니다.</font>
              <% end %>
            <% else %>
              <%= link_to bulletin_post_path(post.bulletin, post) do %>
                <%= content_tag(:div, truncate( raw( sanitize(post.content, :tags => %w(table tr td), :attributes => %w(id class style) ) ), :length => 70, :omission => "..."), class: "etc") %>
              <% end %>
            <% end %>
          </div>
          
          <%# 빈 여백으로 남겨둘 것. %>
          <div class="col-6 col-sm-6 col-md-6 table_separate hidden-sm-down"></div>
          
          <div align="right" class="col-12 col-sm-12 col-md-6 etc table_separate">
            <%= render 'homes/collect/user_info', post: post %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  
  <div class="d-flex flex-column", style="margin-bottom: 10px; margin-top: 30px;">
    <%= paginate @search_post_results %>
  </div>
  
  <%# 검색엔진 %>
  <%= form_tag searches_path, :method => :get do %>
  <div class="row" style="margin-bottom: 100px;">
    <div class="offset-2 offset-sm-3 offset-md-4 col-6 col-sm-5 col-md-3">
      <%= text_field_tag :search, params[:search], required: "true", class: "form-control no-border", placeholder: "제목 또는 내용" %>
    </div>
    <div class="col-2 col-sm-1 col-md-1">
      <%= submit_tag "검색", class: "search_button", :name => nil %>
    </div>
  </div>
  <% end %>
  
</div>