config/routes.rb
Rails.application.routes.draw do
  root "homes#index"

  resources :all_notices
  
  #알림 : 전체 삭제
  get '/new_notifications/read_all' => 'new_notifications#read_all'
  #알림
  resources :new_notifications
  
  resources :qnas do
    post "/report_qna", to: "report_qnas#report_qna_toggle"
    put "/like", to:    "qnas#upvote"
    put "/dislike", to: "qnas#downvote"
  end
  
  resources :searches
  resources :search_all_notices
  resources :search_qnas
  
  resources :bulletins do
    resources :posts do
      put "/like", to:    "posts#upvote"
      put "/dislike", to: "posts#downvote"
      collection do
        get :search
      end
    end
  end
  
  resources :comments do
    put "/like", to:    "comments#upvote"
    put "/dislike", to: "comments#downvote"
    post "/report_comment", to: "report_comments#report_comment_toggle"
    post "/comment_destroys", to: "comment_destroys#comment_destroy_toggle"
  end
  
  resources :bulletins do
    resources :posts
    post "/posts/:post_id/report", to: "reports#report_toggle"
    post "/posts/:post_id/alarm_qna", to: "alarm_qnas#alarm_qna_toggle"
    post "/posts/:post_id/restore", to: "posts#restore"
  end
  
  resources :posts do
    resources :comment_qnas do
        put "/like", to:    "comment_qnas#upvote"
        put "/dislike", to: "comment_qnas#downvote"
      end
  end
  
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  get '/users/message'
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
  #mount ActionCable.server => '/cable'
  
  get '/users/user_list'
  
  #devise_for :users로 인해 별도의 라우터 설정 필요 171012 상열
  resources :users, :only => [:show]
  
  #이미지 업로드 (AWS S3 연동)
  post '/tinymce_assets' => 'tinymce_assets#create'
  
  devise_for :admins
  # 어드민 페이지 및 rails_db
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/views/comments_no_named/_end_of_reply.html.erb
<% comments.order("created_at ASC").each do |comment| %>  
<hr/>
<div class="comments-show">
  <div id="comment<%= comment.id %>"></div>
  <div class="comment">
    <div class="row" style="margin-top: 15px; margin-bottom: 15px;">
      <div class="col-6 col-sm-4 col-md-4 etc">
        <% if can? :for_admin, comment %>
          <b><%= content_tag(:div, "#{comment.nickname}", data: {toggle: "tooltip", placement: "top"}, class: "etc", title: "#{comment.user != nil ? comment.user.nickname : comment.user_name}") %></b>
        <% else %>
          <b><%= comment.nickname %></b>
        <% end %>
      </div>

      <div class="col-6 col-sm-8 col-md-8" align="right">
        <% if not current_user.is_report_comment?(comment) %>
          <% if not (comment.report_comments.size >= comment.num) || (comment.comment_destroys.size >= 1) %>
            <span style="margin-right: 10px;"><%= link_to '<i class="fas fa-cut" aria-hidden="true"></i>'.html_safe, comment_report_comment_path(comment), :method => :post, data: { confirm: '한번 신고 요청 하시면 취소가 안됩니다. 정말 하시겠습니까??' }, class: "badge badge-pill badge-danger" %></span>
            <span style="margin-right: 10px;">|</span>
          <% end %>
        <% end %>
        <% if can? :destroy, comment %>
          <% if not comment.comment_destroys.size >= 1 %>
            <% if not comment.report_comments.size >= comment.num %>
              <span><%= link_to "", comment_comment_destroys_path(comment), class: "fas fa-times", :method => :post, data: { confirm: "정말로 지우시겠습니까?" } %></span>
              <%#= link_to "", comment_path(comment), method: :delete, remote: false, data: { confirm: "정말로 지우시겠습니까?" }, class: "fas fa-times" %>
            <% elsif (comment.report_comments.size >= comment.num) && (current_user.has_role? :admin) %>
              <%= link_to "", comment_path(comment), method: :delete, remote: false, data: { confirm: "이번에 지우면 로그 기록에서도 영영 사라집니다. 정말 지우시겠습니까?" }, class: "fas fa-times", style: "color: red" %>
            <% end %>
          <% elsif (comment.comment_destroys.size >= 1) && (current_user.has_role? :admin) %>
            <%= link_to "", comment_path(comment), method: :delete, remote: false, data: { confirm: "이번에 지우면 로그 기록에서도 영영 사라집니다. 정말 지우시겠습니까?" }, class: "fas fa-times", style: "color: red" %>
          <% end %>
        <% end %>
      </div>
    </div>
      
    <div class="row">
      <div class="col-12 col-sm-12 col-md-12" style="">
        <% if comment.comment_destroys.size >= 1 %>
          <% if can? :for_admin, comment %>
            <font color="red"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 삭제된 댓글</font><br/>
            <b style="color: #6E6E6E;"><%= content_tag(:div, comment.body.html_safe, style: "white-space: pre-wrap;") %></b>
          <% else %>
            <font color="#6E6E6E"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 삭제된 댓글입니다.</font>
          <% end %>
        <% else %>
          <% if comment.report_comments.size >= comment.num %>
            <% if can? :for_admin, comment %>
              <font color="red"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 신고 처리된 댓글</font><br/>
              <b style="color: #6E6E6E;"><%= content_tag(:div, comment.body.html_safe, style: "white-space: pre-wrap;") %></b>
            <% else %>
              <font color="#6E6E6E"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 신고 처리된 댓글입니다.</font>
            <% end %>
          <% else %>
            <%= content_tag(:div, comment.body, style: "white-space: pre-wrap;") %>
          <% end %>
        <% end %>
        <div align="right">
          <% if can? :title, @post %>
            <%= content_tag(:small, "IP : #{comment.remote_ip.split('.').take(2).join('.')}.*.*", data: {toggle: "tooltip", placement: "top"}, title: "#{comment.remote_ip}") %><br/>
          <% else %>
            <%= content_tag(:small, "IP : #{comment.remote_ip.split('.').take(2).join('.')}.*.*") %><br/>
          <% end %>
          <small class="hidden-md-up"><%= time_ago_in_words(comment.created_at) %>전</small>
          <small class="hidden-sm-down" style="margin-right: 10px;"><%= time_ago_in_words(comment.created_at) %>전 (<%= comment.created_at.strftime('%Y-%m-%d %H:%M') %>)</small>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/comments_no_named/_form.html.erb
<% if (not current_user.has_any_role? :block_yellow, :block_red) || (current_user.has_role? :admin) %>
  <%= form_for @new_comment do |f| %>  
    <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
    <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
    <div class="field form-group">
      <%= f.text_field :nickname, class: "form-control no-border col-5 col-sm-4 col-md-3", placeholder: '닉네임(가명)', required: "true" %>
      <%= f.text_area :body, class: 'form-control', style: "margin-top: 10px;", placeholder: '마음의 상처를 입히는 댓글은 피해주세요..ㅠ_ㅠ', required: "true" %><br/>
        <%= submit_tag "댓글", class: 'btn btn-info', style: "float: right" %><br/><br/>
    </div>
  <% end %>
<% end %>

app/views/comments_no_named/_reply.html.erb
<% comments.order("created_at ASC").with_deleted.each do |comment| %>  
<div class="more_comment_list">
  <div class="comments-show">
    <div id="comment<%= comment.id %>"></div>
    <div class="comment">
      <div class="row" style="margin-top: 15px; margin-bottom: 15px;">
        <div class="col-6 col-sm-4 col-md-4 etc">
          <% if can? :for_admin, comment %>
            <b><%= content_tag(:div, "#{comment.nickname}", data: {toggle: "tooltip", placement: "top"}, class: "etc", title: "#{comment.user != nil ? comment.user.nickname : comment.user_name}") %></b>
          <% else %>
            <b><%= comment.nickname %></b>
          <% end %>
        </div>
  
        <div class="col-6 col-sm-8 col-md-8" align="right">
          <% if not current_user.is_report_comment?(comment) %>
            <% if not (comment.report_comments.size >= comment.num) || (comment.comment_destroys.size >= 1) %>
              <span style="margin-right: 10px;"><%= link_to '<i class="fas fa-cut" aria-hidden="true"></i>'.html_safe, comment_report_comment_path(comment), :method => :post, data: { confirm: '한번 신고 요청 하시면 취소가 안됩니다. 정말 하시겠습니까??' }, class: "badge badge-pill badge-danger" %></span>
              <span style="margin-right: 10px;">|</span>
            <% end %>
          <% end %>
          <span style="margin-right: 10px;"><a onclick="showHide('comment_<%= comment.id %>')" onfocus="this.blur()">답글</a></span>
          <% if can? :destroy, comment %>
            <% if not comment.comment_destroys.size >= 1 %>
              <% if not comment.report_comments.size >= comment.num %>
                <span style="margin-right: 10px;">|</span>
                <span><%= link_to "", comment_comment_destroys_path(comment), class: "fas fa-times", :method => :post, data: { confirm: "정말로 지우시겠습니까?" } %></span>
              <% elsif (comment.report_comments.size >= comment.num) && (current_user.has_role? :admin) %>
                <span style="margin-right: 10px;">|</span>
                <%= link_to "", comment_path(comment), method: :delete, remote: false, data: { confirm: "이번에 지우면 로그 기록에서도 영영 사라지며, 대댓글도 함께 삭제됩니다. 정말 지우시겠습니까?" }, class: "fas fa-times", style: "color: red" %>
              <% end %>
            <% elsif (comment.comment_destroys.size >= 1) && (current_user.has_role? :admin) %>
              <span style="margin-right: 10px;">|</span>
              <%= link_to "", comment_path(comment), method: :delete, remote: false, data: { confirm: "이번에 지우면 로그 기록에서도 영영 사라지며, 대댓글도 함께 삭제됩니다. 정말 지우시겠습니까?" }, class: "fas fa-times", style: "color: red" %>
            <% end %>
          <% end %>
        </div>
      </div>
        
      <div class="row">
        <div class="col-12 col-sm-12 col-md-12" style="">
          <% if comment.comment_destroys.size >= 1 %>
            <% if can? :for_admin, comment %>
              <font color="red"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 삭제된 댓글</font><br/>
              <% if comment.user.has_role? :admin %>
                <b style="color: #6E6E6E;"><%= comment.body.html_safe %></b>
              <% else %>
                <b style="color: #6E6E6E;"><%= comment.body %></b>
              <% end %>
            <% else %>
              <font color="#6E6E6E"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 삭제된 댓글입니다.</font>
            <% end %>
          <% else %>
            <% if comment.report_comments.size >= comment.num %>
              <% if can? :for_admin, comment %>
                <font color="red"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 신고 처리된 댓글</font><br/>
                <b style="color: #6E6E6E;"><%= comment.body %></b>
              <% else %>
                <font color="#6E6E6E"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 신고 처리된 댓글입니다.</font>
              <% end %>
            <% else %>
              <% if comment.user.has_role? :admin %>
                <%= comment.body.html_safe %>
              <% else %>
                <%= comment.body %>
              <% end %>
            <% end %>
          <% end %>
          <div align="right">
            <% if can? :ip, @post %>
              <%= content_tag(:small, "IP : #{@post.remote_ip.split('.').take(2).join('.')}.*.*", data: {toggle: "tooltip", placement: "top"}, title: "#{@post.remote_ip}") %><br/>
            <% else %>
              <%= content_tag(:small, "IP : #{@post.remote_ip.split('.').take(2).join('.')}.*.*") %><br/>
            <% end %>
            <small class="hidden-sm-down" style="margin-right: 10px;"><%= time_ago_in_words(comment.created_at) %>전 (<%= comment.created_at.strftime('%Y-%m-%d %H:%M') %>)</small>
            <small class="hidden-md-up"><%= time_ago_in_words(comment.created_at) %>전</small>
          </div>
        </div>
        
        <div class="offset-1 offset-sm-1 offset-md-1 col-11 col-sm-11 col-md-11" style="">
          <%= render partial: "comments_no_named/end_of_reply", locals: {comments: comment.children} %>
        </div>
      </div>
      
      <div id="comment_<%= comment.id %>" style="display:none;">
        <div class="reply-form">
          <%= form_for @new_comment do |f| %>
            <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
            <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
            <%= f.hidden_field :comment_id, value: comment.id %>
            <hr/>
            <div class="col-12 col-sm-12 col-md-12 field form-group" style="margin-top: 30px;">
              <%= f.text_field :nickname, class: "form-control no-border col-5 col-sm-4 col-md-3", placeholder: '닉네임(가명)', required: "true" %>
              <%= f.text_area :body, class: 'form-control', placeholder: '마음의 상처를 입히는 댓글은 피해주세요..ㅠ_ㅠ', style: "margin-top: 10px;", required: "true" %>
            </div>
            <div class="offset-0 offset-sm-10 offset-md-11 col-0 col-sm-2 col-md-1">
              <div class="field form-group">
                <%= submit_tag "답글 달기", class: 'btn btn-info btn-sm', style: "float: right;" %><br/><br/>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <hr/>
</div>
<% end %>

<% if comments.count > 10 %>
  <%= link_to "#", id: "load" do %>
    <%= content_tag(:div, "댓글 더 보기 (+5)", align: "center", class: "more_comment_button", style: "margin-bottom: 30px;") %>
  <% end %>
<% end %>

app/views/comments_no_named/_reply_ASC.html.erb
<% comments.order("created_at ASC").with_deleted.each do |comment| %>  
<div class="more_comment_list">
  <div class="comments-show">
    <div id="comment<%= comment.id %>"></div>
    <div class="comment">
      <div class="row" style="margin-top: 15px; margin-bottom: 15px;">
        <div class="col-6 col-sm-4 col-md-4 etc">
          <% if can? :for_admin, comment %>
            <b><%= content_tag(:div, "#{comment.nickname}", data: {toggle: "tooltip", placement: "top"}, class: "etc", title: "#{comment.user != nil ? comment.user.nickname : comment.user_name}") %></b>
          <% else %>
            <b><%= comment.nickname %></b>
          <% end %>
        </div>
  
        <div class="col-6 col-sm-8 col-md-8" align="right">
          <% if not current_user.is_report_comment?(comment) %>
            <% if not (comment.report_comments.size >= comment.num) || (comment.comment_destroys.size >= 1) %>
              <span style="margin-right: 10px;"><%= link_to '<i class="fas fa-cut" aria-hidden="true"></i>'.html_safe, comment_report_comment_path(comment), :method => :post, data: { confirm: '한번 신고 요청 하시면 취소가 안됩니다. 정말 하시겠습니까??' }, class: "badge badge-pill badge-danger" %></span>
              <span style="margin-right: 10px;">|</span>
            <% end %>
          <% end %>
          <span style="margin-right: 10px;"><a onclick="showHide('comment_<%= comment.id %>')" onfocus="this.blur()">답글</a></span>
          <% if can? :destroy, comment %>
            <% if not comment.comment_destroys.size >= 1 %>
              <% if not comment.report_comments.size >= comment.num %>
                <span style="margin-right: 10px;">|</span>
                <span><%= link_to "", comment_comment_destroys_path(comment), class: "fas fa-times", :method => :post, data: { confirm: "정말로 지우시겠습니까?" } %></span>
              <% elsif (comment.report_comments.size >= comment.num) && (current_user.has_role? :admin) %>
                <span style="margin-right: 10px;">|</span>
                <%= link_to "", comment_path(comment), method: :delete, remote: false, data: { confirm: "이번에 지우면 로그 기록에서도 영영 사라지며, 대댓글도 함께 삭제됩니다. 정말 지우시겠습니까?" }, class: "fas fa-times", style: "color: red" %>
              <% end %>
            <% elsif (comment.comment_destroys.size >= 1) && (current_user.has_role? :admin) %>
              <span style="margin-right: 10px;">|</span>
              <%= link_to "", comment_path(comment), method: :delete, remote: false, data: { confirm: "이번에 지우면 로그 기록에서도 영영 사라지며, 대댓글도 함께 삭제됩니다. 정말 지우시겠습니까?" }, class: "fas fa-times", style: "color: red" %>
            <% end %>
          <% end %>
        </div>
      </div>
        
      <div class="row">
        <div class="col-12 col-sm-12 col-md-12" style="">
          <% if comment.comment_destroys.size >= 1 %>
            <% if can? :for_admin, comment %>
              <font color="red"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 삭제된 댓글</font><br/>
              <% if comment.user.has_role? :admin %>
                <b style="color: #6E6E6E;"><%= content_tag(:div, comment.body.html_safe, style: "white-space: pre-wrap;") %></b>
              <% else %>
                <b style="color: #6E6E6E;"><%= content_tag(:div, comment.body, style: "white-space: pre-wrap;") %></b>
              <% end %>
            <% else %>
              <font color="#6E6E6E"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 삭제된 댓글입니다.</font>
            <% end %>
          <% else %>
            <% if comment.report_comments.size >= comment.num %>
              <% if can? :for_admin, comment %>
                <font color="red"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 신고 처리된 댓글</font><br/>
                <b style="color: #6E6E6E;"><%= content_tag(:div, comment.body.html_safe, style: "white-space: pre-wrap;") %></b>
              <% else %>
                <font color="#6E6E6E"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 신고 처리된 댓글입니다.</font>
              <% end %>
            <% else %>
              <% if comment.user.has_role? :admin %>
                <%= content_tag(:div, comment.body.html_safe, style: "white-space: pre-wrap;") %>
              <% else %>
                <%= content_tag(:div, comment.body, style: "white-space: pre-wrap;") %>
              <% end %>
            <% end %>
          <% end %>
          <div align="right">
            <% if can? :ip, @post %>
              <%= content_tag(:small, "IP : #{comment.remote_ip.split('.').take(2).join('.')}.*.*", data: {toggle: "tooltip", placement: "top"}, title: "#{comment.remote_ip}") %><br/>
            <% else %>
              <%= content_tag(:small, "IP : #{comment.remote_ip.split('.').take(2).join('.')}.*.*") %><br/>
            <% end %>
            <small class="hidden-sm-down" style="margin-right: 10px;"><%= time_ago_in_words(comment.created_at) %>전 (<%= comment.created_at.strftime('%Y-%m-%d %H:%M') %>)</small>
            <small class="hidden-md-up"><%= time_ago_in_words(comment.created_at) %>전</small>
          </div>
        </div>
        
        <div class="offset-1 offset-sm-1 offset-md-1 col-11 col-sm-11 col-md-11" style="">
          <%= render partial: "comments_no_named/end_of_reply", locals: {comments: comment.children} %>
        </div>
      </div>
      
      <div id="comment_<%= comment.id %>" style="display:none;">
        <div class="reply-form">
          <%= form_for @new_comment do |f| %>
            <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
            <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
            <%= f.hidden_field :comment_id, value: comment.id %>
            <hr/>
            <div class="col-12 col-sm-12 col-md-12 field form-group" style="margin-top: 30px;">
              <%= f.text_field :nickname, class: "form-control no-border col-5 col-sm-4 col-md-3", placeholder: '닉네임(가명)', required: "true" %>
              <%= f.text_area :body, class: 'form-control', placeholder: '마음의 상처를 입히는 댓글은 피해주세요..ㅠ_ㅠ', style: "margin-top: 10px;", required: "true" %>
            </div>
            <div class="offset-0 offset-sm-10 offset-md-11 col-0 col-sm-2 col-md-1">
              <div class="field form-group">
                <%= submit_tag "답글 달기", class: 'btn btn-info btn-sm', style: "float: right;" %><br/><br/>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <hr/>
</div>
<% end %>

<% if comments.count > 10 %>
  <%= link_to "#", id: "load" do %>
    <%= content_tag(:div, "댓글 더 보기 (+5)", align: "center", class: "more_comment_button", style: "margin-bottom: 30px;") %>
  <% end %>
<% end %>

app/views/comments_no_named/_reply_DESC.html.erb
<% comments.order("created_at DESC").each do |comment| %>
<div class="more_comment_list">
  <div class="comments-show">
    <div id="comment<%= comment.id %>"></div>
    <div class="comment">
      <div class="row" style="margin-top: 15px; margin-bottom: 15px;">
        <div class="col-6 col-sm-4 col-md-4 etc">
          <% if can? :for_admin, comment %>
            <b><%= content_tag(:div, "#{comment.nickname}", data: {toggle: "tooltip", placement: "top"}, class: "etc", title: "#{comment.user != nil ? comment.user.nickname : comment.user_name}") %></b>
          <% else %>
            <b><%= comment.nickname %></b>
          <% end %>
        </div>
  
        <div class="col-6 col-sm-8 col-md-8" align="right">
          <% if not current_user.is_report_comment?(comment) %>
            <% if not (comment.report_comments.size >= comment.num) || (comment.comment_destroys.size >= 1) %>
              <span style="margin-right: 10px;"><%= link_to '<i class="fas fa-cut" aria-hidden="true"></i>'.html_safe, comment_report_comment_path(comment), :method => :post, data: { confirm: '한번 신고 요청 하시면 취소가 안됩니다. 정말 하시겠습니까??' }, class: "badge badge-pill badge-danger" %></span>
              <span style="margin-right: 10px;">|</span>
            <% end %>
          <% end %>
          <span style="margin-right: 10px;"><a onclick="showHide('comment_<%= comment.id %>')" onfocus="this.blur()">답글</a></span>
          <% if can? :destroy, comment %>
            <% if not comment.comment_destroys.size >= 1 %>
              <% if not comment.report_comments.size >= comment.num %>
                <span style="margin-right: 10px;">|</span>
                <span><%= link_to "", comment_comment_destroys_path(comment), class: "fas fa-times", :method => :post, data: { confirm: "정말로 지우시겠습니까?" } %></span>
              <% elsif (comment.report_comments.size >= comment.num) && (current_user.has_role? :admin) %>
                <span style="margin-right: 10px;">|</span>
                <%= link_to "", comment_path(comment), method: :delete, remote: false, data: { confirm: "이번에 지우면 로그 기록에서도 영영 사라지며, 대댓글도 함께 삭제됩니다. 정말 지우시겠습니까?" }, class: "fas fa-times", style: "color: red" %>
              <% end %>
            <% elsif (comment.comment_destroys.size >= 1) && (current_user.has_role? :admin) %>
              <span style="margin-right: 10px;">|</span>
              <%= link_to "", comment_path(comment), method: :delete, remote: false, data: { confirm: "이번에 지우면 로그 기록에서도 영영 사라지며, 대댓글도 함께 삭제됩니다. 정말 지우시겠습니까?" }, class: "fas fa-times", style: "color: red" %>
            <% end %>
          <% end %>
        </div>
      </div>
        
      <div class="row">
        <div class="col-12 col-sm-12 col-md-12" style="">
          <% if comment.comment_destroys.size >= 1 %>
            <% if can? :for_admin, comment %>
              <font color="red"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 삭제된 댓글</font><br/>
              <% if comment.user.has_role? :admin %>
                <b style="color: #6E6E6E;"><%= content_tag(:div, comment.body.html_safe, style: "white-space: pre-wrap;") %></b>
              <% else %>
                <b style="color: #6E6E6E;"><%= content_tag(:div, comment.body, style: "white-space: pre-wrap;") %></b>
              <% end %>
            <% else %>
              <font color="#6E6E6E"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 삭제된 댓글입니다.</font>
            <% end %>
          <% else %>
            <% if comment.report_comments.size >= comment.num %>
              <% if can? :for_admin, comment %>
                <font color="red"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 신고 처리된 댓글</font><br/>
                <b style="color: #6E6E6E;"><%= content_tag(:div, comment.body.html_safe, style: "white-space: pre-wrap;") %></b>
              <% else %>
                <font color="#6E6E6E"><i class="fas fa-exclamation-triangle" aria-hidden="true"></i> 신고 처리된 댓글입니다.</font>
              <% end %>
            <% else %>
              <% if comment.user.has_role? :admin %>
                <%= content_tag(:div, comment.body.html_safe, style: "white-space: pre-wrap;") %>
              <% else %>
                <%= content_tag(:div, comment.body, style: "white-space: pre-wrap;") %>
              <% end %>
            <% end %>
          <% end %>
          <div align="right">
            <% if can? :ip, @post %>
              <%= content_tag(:small, "IP : #{comment.remote_ip.split('.').take(2).join('.')}.*.*", data: {toggle: "tooltip", placement: "top"}, title: "#{comment.remote_ip}") %><br/>
            <% else %>
              <%= content_tag(:small, "IP : #{comment.remote_ip.split('.').take(2).join('.')}.*.*") %><br/>
            <% end %>
            <small class="hidden-sm-down" style="margin-right: 10px;"><%= time_ago_in_words(comment.created_at) %>전 (<%= comment.created_at.strftime('%Y-%m-%d %H:%M') %>)</small>
            <small class="hidden-md-up"><%= time_ago_in_words(comment.created_at) %>전</small>
          </div>
        </div>
        
        <div class="offset-1 offset-sm-1 offset-md-1 col-11 col-sm-11 col-md-11" style="">
          <%= render partial: "comments_no_named/end_of_reply", locals: {comments: comment.children} %>
        </div>
      </div>
      
      <div id="comment_<%= comment.id %>" style="display:none;">
        <div class="reply-form">
          <%= form_for @new_comment do |f| %>
            <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
            <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
            <%= f.hidden_field :comment_id, value: comment.id %>
            <hr/>
            <div class="col-12 col-sm-12 col-md-12 field form-group" style="margin-top: 30px;">
              <%= f.text_field :nickname, class: "form-control no-border col-5 col-sm-4 col-md-3", placeholder: '닉네임(가명)', required: "true" %>
              <%= f.text_area :body, class: 'form-control', placeholder: '마음의 상처를 입히는 댓글은 피해주세요..ㅠ_ㅠ', style: "margin-top: 10px;", required: "true" %>
            </div>
            <div class="offset-0 offset-sm-10 offset-md-11 col-0 col-sm-2 col-md-1">
              <div class="field form-group">
                <%= submit_tag "답글 달기", class: 'btn btn-info btn-sm', style: "float: right;" %><br/><br/>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <hr/>
</div>
<% end %>

<% if comments.count > 10 %>
  <%= link_to "#", id: "load" do %>
    <%= content_tag(:div, "댓글 더 보기 (+5)", align: "center", class: "more_comment_button", style: "margin-bottom: 30px;") %>
  <% end %>
<% end %>

app/views/comments_no_named/_template.html.erb
<div class="comments-container">
    <% if commentable.comment_threads.count < 30 %>
        <%# 최신글일 수록 아래에 %>
        <%= render partial: "comments_no_named/reply_ASC", locals: {comments: commentable.root_comments} %>
    <% else %>
        <%# 최신글일 수록 위에 %>
        <%= render partial: "comments_no_named/reply_DESC", locals: {comments: commentable.root_comments} %>
    <% end %>
</div>

<%= render partial: "comments_no_named/form", locals: {new_comment: new_comment} %>